Data Encoding
1.nominal/OHE encoding (one hot encoding)
2. Labeland ordinal Encoding
2. Target Guided Ordinal Encodeing

Nominal/OHE encoding
One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as a numerical data which is more suitable for machine learning algorithms.
In this technique, each category is represented as a binary vector, where each bit corresponds to
a unique category.

For example, if we have a categorical variable color with three possible values like red, green,

blue, then we can represent this using one hot encoding like 100010001.

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [15]:
# create dataframe
df=pd.DataFrame({
    'color':['red','blue','green','red','blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [4]:
#create the instance of encoder
encoder=OneHotEncoder()

In [5]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [8]:
import pandas as pd
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [9]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [ ]:
#for new data
encoder.transform([['blue']]).toarray()

d:\ml\myenv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [44]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

LabelEncoding
Label encoding and ordinal encoding are two techniques used to encode categorical

data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable.
for ex:
Red=1,
green=2
blue=3

In [12]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [18]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()
lbl_encoder.fit_transform(df[['color']])

d:\ml\myenv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 2, 0])

In [19]:
lbl_encoder.transform([['red']])

d:\ml\myenv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

ordinal encoding  assign ranks
echnique, each category is assigned a numerical value based on its position in the order.

For example, if we have a categorical variable education level with four possible values like high

school, college graduate, and post graduate, we can represent it using ordinal encoding.
high school=1
college=2
graduate=3
post _gd=4

In [26]:
from sklearn.preprocessing import OrdinalEncoder

In [27]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','large','small']
    
})

In [28]:
df

     size
0   small
1  medium
2   large
3  medium
4   large
5   small

In [31]:
od_encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [32]:
od_encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.]])

In [33]:
od_encoder.transform([['small']])

d:\ml\myenv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

TargetGuided Ordinal Encoding
It is a technique used to encode categorical variable based on the relationship with the target variable. This encoding technique is useful when we have categorical variable with a large number of unique categories.

we replace each category in the categorical variable

with the numerical value based on the mean or median of the target variable for that category.

In [38]:
import pandas as pd
df=pd.DataFrame({
    'city':['nyc','london','paris','tokyo','nyc','paris'],
    'price':[200,400,800,250,320,350]
})

In [39]:
df

     city  price
0     nyc    200
1  london    400
2   paris    800
3   tokyo    250
4     nyc    320
5   paris    350

In [40]:
mean_price=df.groupby('city')['price'].mean()

In [41]:
df['city_encoded']=df['city'].map(mean_price)
df

     city  price  city_encoded
0     nyc    200         260.0
1  london    400         400.0
2   paris    800         575.0
3   tokyo    250         250.0
4     nyc    320         260.0
5   paris    350         575.0

In [43]:
df[['price','city_encoded']]

   price  city_encoded
0    200         260.0
1    400         400.0
2    800         575.0
3    250         250.0
4    320         260.0
5    350         575.0

In [50]:
import seaborn as sns
tips=sns.load_dataset('tips')
x=tips[['day']]
y=tips['total_bill']
mean_target=tips.groupby('day')['total_bill'].mean()

In [52]:
x['days']=x['day'].map(mean_target)
x

      day       days
0     Sun  21.410000
1     Sun  21.410000
2     Sun  21.410000
3     Sun  21.410000
4     Sun  21.410000
..    ...        ...
239   Sat  20.441379
240   Sat  20.441379
241   Sat  20.441379
242   Sat  20.441379
243  Thur  17.682742

[244 rows x 2 columns]