PANDAS 
pandas is a powerful data manipulation library in Python, widely used for data analysis and cleaning.
It provides two primary data structures series and data frame.
We'll understand the difference between series and data frame.

A series is one dimensional array like object, while a data frame is a two dimensional size, mutable

and potentially heterogeneous tabular data structure with labeled axis.

Okay, so the basic difference between series and data frame is a series is the one dimensional like

array object, like how we create a one dimensional array in NumPy.

In [4]:

import pandas as pd

In [7]:
#series Panda series is a one dimensional array like object that can hold any data type.It is similar to a column in a table.
data=[1,2,3,4,5]
series=pd.Series(data)
print("series",series)
print(type(series))

series 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [9]:
#create a series from dictionaries
data={"a":1,"b":2,"c":3}
series=pd.Series(data)
print(series)
print(type(series))

a    1
b    2
c    3
dtype: int64
<class 'pandas.Series'>

In [12]:
data=[1,2,3,4]
index=['a','b','c','d']
pd.Series(data,index=index)

a    1
b    2
c    3
d    4
dtype: int64

In [14]:
#dataframe
#create the datafraom from dict
data={
    'name':['kri','ojn','ma'],
    'age':[12,34,55],
    'city':['bangolar','pune','nyx']
}
df=pd.DataFrame(data)
print(df)

  name  age      city
0  kri   12  bangolar
1  ojn   34      pune
2   ma   55       nyx

In [15]:
import numpy as np
np.array(df)

array([['kri', 12, 'bangolar'],
       ['ojn', 34, 'pune'],
       ['ma', 55, 'nyx']], dtype=object)

In [30]:
#create df from dist of dict
data=[
    {'name':'kri','age':23,'city':'bangalore'},
    {'name':'joh','age':43,'city':'nyc'},
    {'name':'ani','age':53,'city':'pune'}
]
df=pd.DataFrame(data)
print(df)

  name  age       city
0  kri   23  bangalore
1  joh   43        nyc
2  ani   53       pune

In [34]:
# df['name']
df.loc[0]
df.iloc[0]

name          kri
age            23
city    bangalore
Name: 0, dtype: object

In [38]:
df.at[1,'age']

np.int64(43)

In [39]:
df.at[2,'name']

'ani'

In [40]:
df.iat[2,2]

'pune'

In [42]:
#data manupilation with data frame
df['sal']=[4000,5000,6000]
df

  name  age       city   sal
0  kri   23  bangalore  4000
1  joh   43        nyc  5000
2  ani   53       pune  6000

In [ ]:
#remove
df.drop('sal',axis=1,inplace=True)
#axis=1 for the column and inplace =true for the permanent deletion

In [47]:
df

  name  age       city   sal
0  kri   23  bangalore  4000
1  joh   43        nyc  5000
2  ani   53       pune  6000

In [51]:
df['age']=df['age']+1
df

  name  age       city
0  kri   25  bangalore
1  joh   45        nyc
2  ani   55       pune

In [64]:
df.drop(1,axis=0)

,Formatted_Date,Summary,Precip_Type,Temperature (C),Apparent_Temperature_C,Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.
5,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,9.222222,7.111111,0.85,13.9587,258,14.9569,0,1016.66,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.

In [65]:
df=pd.read_csv(r"C:\Users\RAJDEEP\Downloads\archive (17)\weatherHistory.csv") 
df

,Formatted_Date,Summary,Precip_Type,Temperature (C),Apparent_Temperature_C,Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.

In [66]:
df.describe()

,Temperature (C),Apparent_Temperature_C,Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
count,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.0,96453.000000
mean,11.932678,10.855029,0.734899,10.810640,187.509232,10.347325,0.0,1003.235956
std,9.551546,10.696847,0.195473,6.913571,107.383428,4.192123,0.0,116.969906
min,-21.822222,-27.716667,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,4.688889,2.311111,0.600000,5.828200,116.000000,8.339800,0.0,1011.900000
50%,12.000000,12.000000,0.780000,9.965900,180.000000,10.046400,0.0,1016.450000
75%,18.838889,18.838889,0.890000,14.135800,290.000000,14.812000,0.0,1021.090000
max,39.905556,39.344444,1.000000,63.852600,359.000000,16.100000,0.0,1046.380000