FEATURES
The various features of the cleaned dataset are explained below:
1) Airline: The name of the airline company is stored in the airline column. It is a categorical feature having 6 different airlines.
2) Flight: Flight stores information regarding the plane's flight code. It is a categorical feature.
3) Source City: City from which the flight takes off. It is a categorical feature having 6 unique cities.
4) Departure Time: This is a derived categorical feature obtained created by grouping time periods into bins. It stores information about the departure time and have 6 unique time labels.
5) Stops: A categorical feature with 3 distinct values that stores the number of stops between the source and destination cities.
6) Arrival Time: This is a derived categorical feature created by grouping time intervals into bins. It has six distinct time labels and keeps information about the arrival time.
7) Destination City: City where the flight will land. It is a categorical feature having 6 unique cities.
8) Class: A categorical feature that contains information on seat class; it has two distinct values: Business and Economy.
9) Duration: A continuous feature that displays the overall amount of time it takes to travel between cities in hours.
10)Days Left: This is a derived characteristic that is calculated by subtracting the trip date by the booking date.
11) Price: Target variable stores information of the ticket price.

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns

In [18]:
df=pd.read_csv(r"C:\Users\RAJDEEP\Downloads\archive (21)\economy.csv")

In [19]:
df.tail()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
206769,31-03-2022,Vistara,UK,832,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"7,697"
206770,31-03-2022,Vistara,UK,832,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"7,709"
206771,31-03-2022,Vistara,UK,826,12:30,Chennai,20h 35m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,"8,640"
206772,31-03-2022,Vistara,UK,822,09:45,Chennai,23h 20m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,09:05,Hyderabad,"8,640"
206773,31-03-2022,Vistara,UK,824,20:30,Chennai,24h 25m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"8,640"

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        206774 non-null  str
 1   airline     206774 non-null  str
 2   ch_code     206774 non-null  str
 3   num_code    206774 non-null  int64
 4   dep_time    206774 non-null  str
 5   from        206774 non-null  str
 6   time_taken  206774 non-null  str
 7   stop        206774 non-null  str
 8   arr_time    206774 non-null  str
 9   to          206774 non-null  str
 10  price       206774 non-null  str
dtypes: int64(1), str(10)
memory usage: 33.8 MB

In [21]:
df['Date']=df['date'].str.split('-').str[0]
df['month']=df['date'].str.split('-').str[1]
df['year']=df['date'].str.split('-').str[2]

In [23]:
df['Date'].astype(int)
df['month'].astype(int)
df['year'].astype(int)

0         2022
1         2022
2         2022
3         2022
4         2022
          ...
206769    2022
206770    2022
206771    2022
206772    2022
206773    2022
Name: year, Length: 206774, dtype: int64

In [24]:
df.info

<bound method DataFrame.info of               date   airline ch_code  num_code dep_time     from time_taken  \
0       11-02-2022  SpiceJet      SG      8709    18:55    Delhi    02h 10m
1       11-02-2022  SpiceJet      SG      8157    06:20    Delhi    02h 20m
2       11-02-2022   AirAsia      I5       764    04:25    Delhi    02h 10m
3       11-02-2022   Vistara      UK       995    10:20    Delhi    02h 15m
4       11-02-2022   Vistara      UK       963    08:50    Delhi    02h 20m
...            ...       ...     ...       ...      ...      ...        ...
206769  31-03-2022   Vistara      UK       832    07:05  Chennai    13h 50m
206770  31-03-2022   Vistara      UK       832    07:05  Chennai    13h 50m
206771  31-03-2022   Vistara      UK       826    12:30  Chennai    20h 35m
206772  31-03-2022   Vistara      UK       822    09:45  Chennai    23h 20m
206773  31-03-2022   Vistara      UK       824    20:30  Chennai    24h 25m

                                                     stop arr_time         to  \
0                                               non-stop     21:05     Mumbai
1                                               non-stop     08:40     Mumbai
2                                               non-stop     06:35     Mumbai
3                                               non-stop     12:35     Mumbai
4                                               non-stop     11:10     Mumbai
...                                                   ...      ...        ...
206769  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    20:55  Hyderabad
206770  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    20:55  Hyderabad
206771  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    09:05  Hyderabad
206772  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    09:05  Hyderabad
206773  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    20:55  Hyderabad

        price Date month  year
0       5,953   11    02  2022
1       5,953   11    02  2022
2       5,956   11    02  2022
3       5,955   11    02  2022
4       5,955   11    02  2022
...       ...  ...   ...   ...
206769  7,697   31    03  2022
206770  7,709   31    03  2022
206771  8,640   31    03  2022
206772  8,640   31    03  2022
206773  8,640   31    03  2022

[206774 rows x 14 columns]>

In [25]:
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Date,month,year
0,11-02-2022,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",11,02,2022
1,11-02-2022,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",11,02,2022
2,11-02-2022,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",11,02,2022
3,11-02-2022,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",11,02,2022
4,11-02-2022,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",11,02,2022

In [28]:
df.drop('date',axis=1,inplace=True)

In [30]:
df['Hour']=df['arr_time'].str.split(':').str[0]
df['Min']=df['arr_time'].str.split(':').str[1]

In [33]:
df['Hour'].astype(int)
df['Min'].astype(int)
df.drop('arr_time',axis=1,inplace=True)

In [34]:
df.head(2)

,airline,ch_code,num_code,dep_time,from,time_taken,stop,to,price,Date,month,year,Hour,Min
0,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,Mumbai,"5,953",11,02,2022,21,05
1,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,Mumbai,"5,953",11,02,2022,08,40

In [36]:
df['DHour']=df['dep_time'].str.split(':').str[0]
df['DMin']=df['dep_time'].str.split(':').str[1]
df['DHour'].astype(int)
df['DMin'].astype(int)
df.drop('dep_time',axis=1,inplace=True)

In [44]:
df['stop'].isnull()
df['tot_stop']=df['stop'].map({'non-stop':0,'1-stop':1})

In [45]:
df.head(2)

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,month,year,Hour,Min,DHour,DMin,tot_stop
0,SpiceJet,SG,8709,Delhi,02h 10m,non-stop,Mumbai,"5,953",11,02,2022,21,05,18,55,NaN
1,SpiceJet,SG,8157,Delhi,02h 20m,non-stop,Mumbai,"5,953",11,02,2022,08,40,06,20,NaN

In [46]:
df['time_taken'].str.split(' ').str[0].str.split('h').str[0]

0         02
1         02
2         02
3         02
4         02
          ..
206769    13
206770    13
206771    20
206772    23
206773    24
Name: time_taken, Length: 206774, dtype: object

In [48]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()

encoder.fit_transform(df[['airline','from','to']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 620322 stored elements and shape (206774, 20)>

In [49]:
pd.DataFrame(
encoder.fit_transform(df[['airline','from','to']]).toarray(),columns=encoder.get_feature_names_out())

,airline_Air India,airline_AirAsia,airline_GO FIRST,airline_Indigo,airline_SpiceJet,airline_StarAir,airline_Trujet,airline_Vistara,from_Bangalore,from_Chennai,from_Delhi,from_Hyderabad,from_Kolkata,from_Mumbai,to_Bangalore,to_Chennai,to_Delhi,to_Hyderabad,to_Kolkata,to_Mumbai
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206769,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
206770,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
206771,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
206772,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
206773,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0