The problem statement is trips and travel.

Dot com company wants to enable and establish a viable business model to expand the customer base.

One of the ways to expand the customer base is to introduce a new offering of packages.

Currently, there are five types of packages that is uh, basic, standard, deluxe, super, deluxe

King.

Looking at the data of the last year, we observed 18 percentage of the customer purchased the package.

However, the marketing cost was quite high because the customer was contacted at random without looking

at the available information.

The company is now planning to launch a new product wellness Tourism package.

Now, wellness tourism is defined as travel that allows the traveler to maintain, enhance or kick start

a healthy lifestyle and support or increase one's sense of well-being.

However, this time, company wants to harness the available data of existing and potential customers

to mark, uh, to the marketing expenditure.

More efficient.

In [58]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt

In [59]:
df=pd.read_csv(r"C:\Users\RAJDEEP\Downloads\Travel.csv")

In [60]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [61]:
#Data cleaning
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [62]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [63]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [64]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [65]:
df['Gender']=df['Gender'].replace('Fe Male','Female')
df['maritalStatus']=df['MaritalStatus'].replace('Single','unmarried')

In [66]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,...,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome,maritalStatus
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,...,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0,unmarried
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,...,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0,Divorced
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,...,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0,unmarried
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,...,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0,Divorced
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,...,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0,Divorced

In [67]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [68]:
#missing values

feature_with_na=[features for features in df.columns if df[features].isnull().sum()>=1]
for feature in feature_with_na:
    print(feature,np.round(df[feature].isnull().mean()*100,5),'% missing values')

Age 4.62357 % missing values
TypeofContact 0.51146 % missing values
DurationOfPitch 5.13502 % missing values
NumberOfFollowups 0.92062 % missing values
PreferredPropertyStar 0.53191 % missing values
NumberOfTrips 2.86416 % missing values
NumberOfChildrenVisiting 1.35025 % missing values
MonthlyIncome 4.76678 % missing values

In [69]:
df[feature_with_na].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [70]:
df.Age.fillna(df.Age.median(),inplace=True)
df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)
df.DurationOfPitch.fillna(df.DurationOfPitch.median(),inplace=True)
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)
df.NumberOfTrips.fillna(0,inplace=True)
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0],inplace=True)
df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)

C:\Users\RAJDEEP\AppData\Local\Temp\ipykernel_3324\876565064.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.Age.fillna(df.Age.median(),inplace=True)
C:\Users\RAJDEEP\AppData\Local\Temp\ipykernel_3324\876565064.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)
C:\Users\RAJDEEP\AppData\Local\Temp\ipykernel_3324\876565064.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.DurationOfPitch.fillna(df.DurationOfPitch.median(),inplace=True)
C:\Users\RAJDEEP\AppData\Local\Temp\ipykernel_3324\876565064.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)
C:\Users\RAJDEEP\AppData\Local\Temp\ipykernel_3324\876565064.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)
C:\Users\RAJDEEP\AppData\Local\Temp\ipykernel_3324\876565064.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.NumberOfTrips.fillna(0,inplace=True)
C:\Users\RAJDEEP\AppData\Local\Temp\ipykernel_3324\876565064.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0],inplace=True)
C:\Users\RAJDEEP\AppData\Local\Temp\ipykernel_3324\876565064.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)

0       20993.0
1       20130.0
2       17090.0
3       17909.0
4       18468.0
         ...
4883    26576.0
4884    21212.0
4885    31820.0
4886    20289.0
4887    24041.0
Name: MonthlyIncome, Length: 4888, dtype: float64

In [71]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,...,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome,maritalStatus
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,...,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0,unmarried
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,...,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0,Divorced
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,...,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0,unmarried
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,...,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0,Divorced
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,...,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0,Divorced

In [72]:
df.drop('CustomerID',inplace=True,axis=1)

In [73]:
df.isnull().sum()

ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
maritalStatus                 0
dtype: int64

In [74]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome,maritalStatus
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0,unmarried
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0,Divorced
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0,unmarried
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0,Divorced
4,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0,Divorced

In [75]:
df['TotalVisiting']=df['NumberOfPersonVisiting']+df['NumberOfFollowups']
df.drop(columns=['NumberOfPersonVisiting','NumberOfFollowups'])

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome,maritalStatus,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0,unmarried,6.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0,Divorced,7.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0,unmarried,7.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0,Divorced,5.0
4,0,NaN,Self Enquiry,1,8.0,Small Business,Male,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0,Divorced,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0,Unmarried,8.0
4884,1,28.0,Company Invited,1,31.0,Salaried,Male,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0,unmarried,9.0
4885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0,Married,8.0
4886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0,unmarried,7.0
4887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0,Unmarried,8.0

In [76]:
num_features=[feature for feature in df.columns if df[feature].dtype!='O']
print("no of numerical feature", len(num_features))

no of numerical feature 21

In [77]:
cat_features=[feature for feature in df.columns if df[feature].dtype=='O']
print("no of numerical feature", len(cat_features))

no of numerical feature 0

In [78]:
dis_features=[feature for feature in df.columns if len(df[feature].unique())<=25]
print("no of numerical feature", len(dis_features))

no of numerical feature 18

In [79]:
#continuoues featuere
cont_features=[feature for feature in num_features if feature not in dis_features]
print("no of numerical feature", len(cont_features))

no of numerical feature 3

In [80]:
from sklearn.model_selection import train_test_split
x=df.drop(['ProdTaken'],axis=1)
y=df['ProdTaken']

In [81]:
x_t,x_test,y_t,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
x_t.shape

(3421, 20)

In [82]:
cat_features=x.select_dtypes(include='object').columns
num_features=x.select_dtypes(include='object').columns
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')
preprocess=ColumnTransformer(
    [
    ('OneHotEncoder',oh_transformer,cat_features),
    ('StandardScaler',numeric_transformer,num_features)
    ]
)

C:\Users\RAJDEEP\AppData\Local\Temp\ipykernel_3324\2161369124.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features=x.select_dtypes(include='object').columns
C:\Users\RAJDEEP\AppData\Local\Temp\ipykernel_3324\2161369124.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  num_features=x.select_dtypes(include='object').columns

In [83]:
preprocess

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation', 'maritalStatus'],
      dtype='str')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation', 'maritalStatus'],
      dtype='str'))])

In [86]:
x_t.dtypes

Age                         float64
TypeofContact                   str
CityTier                      int64
DurationOfPitch             float64
Occupation                      str
Gender                          str
NumberOfPersonVisiting        int64
NumberOfFollowups           float64
ProductPitched                  str
PreferredPropertyStar       float64
MaritalStatus                   str
NumberOfTrips               float64
Passport                      int64
PitchSatisfactionScore        int64
OwnCar                        int64
NumberOfChildrenVisiting    float64
Designation                     str
MonthlyIncome               float64
maritalStatus                   str
TotalVisiting               float64
dtype: object

In [85]:
#applying transformation in training(fit_transform)
x_t=preprocess.fit_transform(x_t)

ValueError: could not convert string to float: 'Self Enquiry'

In [37]:
x_t

,CustomerID,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome,maritalStatus
736,200736,48.0,Self Enquiry,1,10.0,Salaried,Male,3,4.0,Standard,3.0,Unmarried,1.0,0,5,1,1.0,Senior Manager,25999.0,Unmarried
1615,201615,30.0,Self Enquiry,1,11.0,Large Business,Female,2,3.0,Basic,5.0,Married,6.0,0,5,0,1.0,Executive,18204.0,Married
336,200336,29.0,Self Enquiry,1,14.0,Salaried,Male,3,5.0,Basic,5.0,Divorced,2.0,1,3,1,1.0,Executive,17119.0,Divorced
4526,204526,29.0,Self Enquiry,3,9.0,Small Business,Female,3,4.0,Deluxe,4.0,Married,3.0,1,3,1,2.0,Manager,23457.0,Married
2665,202665,34.0,Self Enquiry,1,11.0,Small Business,Female,3,5.0,Basic,4.0,Divorced,8.0,0,4,0,1.0,Executive,21300.0,Divorced
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4426,204426,28.0,Self Enquiry,1,10.0,Small Business,Male,3,5.0,Basic,3.0,Single,2.0,0,1,1,2.0,Executive,20723.0,unmarried
466,200466,41.0,Self Enquiry,3,8.0,Salaried,Female,3,3.0,Super Deluxe,5.0,Divorced,1.0,0,5,1,1.0,AVP,31595.0,Divorced
3092,203092,38.0,Company Invited,3,28.0,Small Business,Female,3,4.0,Basic,3.0,Divorced,7.0,0,2,1,2.0,Executive,21651.0,Divorced
3772,203772,28.0,Self Enquiry,3,30.0,Small Business,Female,3,5.0,Deluxe,3.0,Married,3.0,0,1,1,2.0,Manager,22218.0,Married
860,200860,22.0,Company Invited,1,9.0,Salaried,Male,2,4.0,Basic,3.0,Divorced,1.0,1,3,0,0.0,Executive,17853.0,Divorced

In [38]:
x_test=preprocess.transform(x_test)

AttributeError: 'ColumnTransformer' object has no attribute 'transformers_'

In [47]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,r2_score,recall_score,precision_score,f1_score,roc_auc_score,classification_report,confusion_matrix

In [ ]:
models={
    'Randon Forest':RandomForestClassifier(),
    'Decision Tree':DecisionTreeClassifier()

}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_t,y_t)
    y_train_pred=model.predict(x_t)
    y_test_pred=model.predict(x_test)
    model_train_acc=accuracy_score(y_t,y_train_pred)
    model_train_f1=f1_score(y_t,y_train_pred,average='weighted')
    model_train_precision=precision_score(y_t,y_train_pred)
    model_train_recall=recall_score(y_t,y_train_pred)
    model_train_rocauc=roc_auc_score(y_t,y_train_pred)
    #test data
    model_test_acc=accuracy_score(y_t,y_test_pred)
    model_test_f1=f1_score(y_t,y_test_pred,average='weighted')
    model_test_precision=precision_score(y_t,y_test_pred)
    model_test_recall=recall_score(y_t,y_test_pred)
    model_test_rocauc=roc_auc_score(y_t,y_test_pred)
    print(list(models.key())[i])
    print("accuracy".format(model_train_acc))
    print("f1_score".format(model_train_f1))
    print("precision_score".format(model_train_precision))
    print("recall_score".format(model_train_recall))
    print("rocauc_score".format(model_train_rocauc))
    #test
    print("test acc".format(model_test_acc))
    print("f1_score".format(model_test_f1))
    print("precision_score".format(model_test_precision))
    print("recall_score".format(model_test_recall))
    print("rocauc_score".format(model_test_rocauc))

ValueError: could not convert string to float: 'Self Enquiry'

In [50]:
#hypreparametre tuning
rf_param={"max_depth":[5,8,15,None,10],
          'max_features':[5,7,'auto','8'],
          'min_samples_split':[2,8,15,20],
          'n_estimators':[100,200,500,1000]
}

In [51]:
randomcv_models=[
    ("RF",RandomForestClassifier(),rf_param)
]

In [54]:
randomcv_models

[('RF',
  RandomForestClassifier(),
  {'max_depth': [5, 8, 15, None, 10],
   'max_features': [5, 7, 'auto', '8'],
   'min_samples_split': [2, 8, 15, 20],
   'n_estimators': [100, 200, 500, 1000]})]

In [53]:
from sklearn.model_selection import RandomizedSearchCV
model_param={}
for name,model,params in randomcv_models:
    random=RandomizedSearchCV(estimator=model,
                              param_distributions=params,
                              n_iter=100,
                              cv=3,verbose=2,
                              n_jobs=-1)

In [55]:
random.fit(x_t,y_t)
model.param[name]=random.best_params_

Fitting 3 folds for each of 100 candidates, totalling 300 fits

ValueError:
All the 300 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
40 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ml\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ml\myenv\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\ml\myenv\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\ml\myenv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ml\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ml\myenv\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\ml\myenv\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\ml\myenv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
141 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ml\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ml\myenv\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\ml\myenv\Lib\site-packages\sklearn\ensemble\_forest.py", line 334, in fit
    X, y = validate_data(
           ~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<5 lines>...
        ensure_all_finite=False,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\ml\myenv\Lib\site-packages\sklearn\utils\validation.py", line 3055, in validate_data
    X, y = check_X_y(X, y, **check_params)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ml\myenv\Lib\site-packages\sklearn\utils\validation.py", line 1327, in check_X_y
    X = check_array(
        X,
    ...<12 lines>...
        input_name="X",
    )
  File "d:\ml\myenv\Lib\site-packages\sklearn\utils\validation.py", line 1035, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "d:\ml\myenv\Lib\site-packages\sklearn\utils\_array_api.py", line 976, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "d:\ml\myenv\Lib\site-packages\pandas\core\generic.py", line 2039, in __array__
    arr = np.asarray(values, dtype=dtype)
ValueError: could not convert string to float: 'Self Enquiry'

--------------------------------------------------------------------------------
43 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ml\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ml\myenv\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\ml\myenv\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\ml\myenv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got '8' instead.

--------------------------------------------------------------------------------
26 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ml\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ml\myenv\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\ml\myenv\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\ml\myenv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got '8' instead.

In [56]:
models={
    'Randon Forest':RandomForestClassifier(n_estimators=1000,min_samples_split=2,max_features=7,max_depth=10),
    'Decision Tree':DecisionTreeClassifier()

}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_t,y_t)
    y_train_pred=model.predict(x_t)
    y_test_pred=model.predict(x_test)
    model_train_acc=accuracy_score(y_t,y_train_pred)
    model_train_f1=f1_score(y_t,y_train_pred,average='weighted')
    model_train_precision=precision_score(y_t,y_train_pred)
    model_train_recall=recall_score(y_t,y_train_pred)
    model_train_rocauc=roc_auc_score(y_t,y_train_pred)
    #test data
    model_test_acc=accuracy_score(y_t,y_test_pred)
    model_test_f1=f1_score(y_t,y_test_pred,average='weighted')
    model_test_precision=precision_score(y_t,y_test_pred)
    model_test_recall=recall_score(y_t,y_test_pred)
    model_test_rocauc=roc_auc_score(y_t,y_test_pred)
    print(list(models.key())[i])
    print("accuracy".format(model_train_acc))
    print("f1_score".format(model_train_f1))
    print("precision_score".format(model_train_precision))
    print("recall_score".format(model_train_recall))
    print("rocauc_score".format(model_train_rocauc))
    #test
    print("test acc".format(model_test_acc))
    print("f1_score".format(model_test_f1))
    print("precision_score".format(model_test_precision))
    print("recall_score".format(model_test_recall))
    print("rocauc_score".format(model_test_rocauc))

ValueError: could not convert string to float: 'Self Enquiry'

In [57]:
print(df.select_dtypes(include='object').columns)

Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation', 'maritalStatus'],
      dtype='str')

C:\Users\RAJDEEP\AppData\Local\Temp\ipykernel_3324\2219242324.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include='object').columns)